SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
        FROM ONLINE_SALE
        WHERE SALES_DATE LIKE '2022-03%'
      UNION ALL
        SELECT OFFLINE_SALE_ID, NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
        FROM OFFLINE_SALE
        WHERE SALES_DATE LIKE '2022-03%'
     ) A
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID